//
// Created by matthias on 12/10/19.
//

#ifndef GBA_SPRITE_ENGINE_PROJECT_MINIONTYPES_H
#define GBA_SPRITE_ENGINE_PROJECT_MINIONTYPES_H

#define SHOOTER_MINION 1
#define FLOWER_MINION 2

#endif //GBA_SPRITE_ENGINE_PROJECT_MINIONTYPES_H
