//
// Created by matthias on 12/1/19.
//

#ifndef GBA_SPRITE_ENGINE_PROJECT_ZOMBIETYPES_H
#define GBA_SPRITE_ENGINE_PROJECT_ZOMBIETYPES_H

#define STANDARD_ZOMBIE 1
#define CONEHEAD_ZOMBIE 2
#define BUCKETHEAD_ZOMBIE 3

#endif //GBA_SPRITE_ENGINE_PROJECT_ZOMBIETYPES_H
